//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDeleteGUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDeleteGUI.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments ERROR!\nOnly one directory must be specifed to clean!.
        /// </summary>
        internal static string E_CMDLINE_ONLY_1_DIR_MUST_BE {
            get {
                return ResourceManager.GetString("E_CMDLINE_ONLY_1_DIR_MUST_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown first CommandLine argument = &apos;{0}&apos;!.
        /// </summary>
        internal static string E_CMDLINE_UNKNOWN_1_ARG {
            get {
                return ResourceManager.GetString("E_CMDLINE_UNKNOWN_1_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Source selected!.
        /// </summary>
        internal static string E_UNKNOWN_SOURCE {
            get {
                return ResourceManager.GetString("E_UNKNOWN_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Files|*.*.
        /// </summary>
        internal static string FILTER_ANY_FILE {
            get {
                return ResourceManager.GetString("FILTER_ANY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to clean:.
        /// </summary>
        internal static string L_CLEAN_TARGET {
            get {
                return ResourceManager.GetString("L_CLEAN_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s):.
        /// </summary>
        internal static string L_CLEAN_TARGET_FILES {
            get {
                return ResourceManager.GetString("L_CLEAN_TARGET_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder and all its contents:.
        /// </summary>
        internal static string L_CLEAN_TARGET_FOLDER {
            get {
                return ResourceManager.GetString("L_CLEAN_TARGET_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical drive (clean free space):.
        /// </summary>
        internal static string L_CLEAN_TARGET_LOG_DISK_FREEE_SPACE {
            get {
                return ResourceManager.GetString("L_CLEAN_TARGET_LOG_DISK_FREEE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty physical disk without partitions:.
        /// </summary>
        internal static string L_CLEAN_TARGET_PHY_DISK {
            get {
                return ResourceManager.GetString("L_CLEAN_TARGET_PHY_DISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partition(s).
        /// </summary>
        internal static string L_DISK_PARTITIONS {
            get {
                return ResourceManager.GetString("L_DISK_PARTITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask me this again.
        /// </summary>
        internal static string L_DONT_ASK_AGAIN {
            get {
                return ResourceManager.GetString("L_DONT_ASK_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} since the beginning.
        /// </summary>
        internal static string L_ELAPSED {
            get {
                return ResourceManager.GetString("L_ELAPSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated.
        /// </summary>
        internal static string L_ESTIMATED {
            get {
                return ResourceManager.GetString("L_ESTIMATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free space cleaning method:.
        /// </summary>
        internal static string L_FREE_SPACE_CLEAN_METHOD {
            get {
                return ResourceManager.GetString("L_FREE_SPACE_CLEAN_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean..
        /// </summary>
        internal static string L_FREE_SPACE_CLEAN_METHOD_CLEAN {
            get {
                return ResourceManager.GetString("L_FREE_SPACE_CLEAN_METHOD_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero (good for virtual disk optimization).
        /// </summary>
        internal static string L_FREE_SPACE_CLEAN_METHOD_ZERO {
            get {
                return ResourceManager.GetString("L_FREE_SPACE_CLEAN_METHOD_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string L_OUTPUT {
            get {
                return ResourceManager.GetString("L_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Passes:.
        /// </summary>
        internal static string L_OVERWRITE_PASS_COUNT {
            get {
                return ResourceManager.GetString("L_OVERWRITE_PASS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass {0}, progress: {1}% ({2} {3}).
        /// </summary>
        internal static string L_PROGRESS {
            get {
                return ResourceManager.GetString("L_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  location: .
        /// </summary>
        internal static string L_SDELETE_LOCATION {
            get {
                return ResourceManager.GetString("L_SDELETE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean with SDelete.
        /// </summary>
        internal static string L_SHELL_MENU_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("L_SHELL_MENU_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register shell context menu.
        /// </summary>
        internal static string L_SHELL_MENU_REGISTER {
            get {
                return ResourceManager.GetString("L_SHELL_MENU_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister shell context menu.
        /// </summary>
        internal static string L_SHELL_MENU_UNREGISTER {
            get {
                return ResourceManager.GetString("L_SHELL_MENU_UNREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string L_START {
            get {
                return ResourceManager.GetString("L_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string L_STOP {
            get {
                return ResourceManager.GetString("L_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading disk list....
        /// </summary>
        internal static string M_LOADING_DISK_LIST {
            get {
                return ResourceManager.GetString("M_LOADING_DISK_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysinternals &apos;{0}&apos; or &apos;{1}&apos; was not found in well-known locations!
        ///Do you want to find it manualy?.
        /// </summary>
        internal static string Q_MANUAL_SEARCH_SDELETE_BINARY {
            get {
                return ResourceManager.GetString("Q_MANUAL_SEARCH_SDELETE_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register in shell context menu for folders cleanup?.
        /// </summary>
        internal static string Q_REGISTER_SHELL_MENU {
            get {
                return ResourceManager.GetString("Q_REGISTER_SHELL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cleanup operation is still in progress!\n\nCancel cleaning?.
        /// </summary>
        internal static string Q_STOP_ACTIVE_CLEANUP {
            get {
                return ResourceManager.GetString("Q_STOP_ACTIVE_CLEANUP", resourceCulture);
            }
        }
    }
}
